# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qr_generate_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# Nearly same as qr_addroid_app but made by PyQt5

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import qrcode, qr_code_generator
from io import BytesIO

qr = qrcode.QRCode(version = 1,
                    error_correction = qrcode.constants.ERROR_CORRECT_L,
                    box_size = 50,
                    border = 10)

class Ui_qr_image_generator(object):
    def setupUi(self, qr_image_generator):
        qr_image_generator.setObjectName("qr_image_generator")
        qr_image_generator.resize(1106, 846)
        self.centralwidget = QtWidgets.QWidget(qr_image_generator)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sure = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sure.setFont(font)
        self.sure.setAlignment(QtCore.Qt.AlignCenter)
        self.sure.setObjectName("sure")
        self.verticalLayout.addWidget(self.sure)
        self.qr_kod = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.qr_kod.setFont(font)
        self.qr_kod.setAlignment(QtCore.Qt.AlignCenter)
        self.qr_kod.setObjectName("qr_kod")
        self.verticalLayout.addWidget(self.qr_kod)
        self.qr_resim = QtWidgets.QLabel(self.centralwidget)
        self.qr_resim.setAlignment(QtCore.Qt.AlignCenter)
        self.qr_resim.setObjectName("qr_resim")
        self.verticalLayout.addWidget(self.qr_resim)
        qr_image_generator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(qr_image_generator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 26))
        self.menubar.setObjectName("menubar")
        qr_image_generator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(qr_image_generator)
        self.statusbar.setObjectName("statusbar")
        qr_image_generator.setStatusBar(self.statusbar)

        self.retranslateUi(qr_image_generator)
        QtCore.QMetaObject.connectSlotsByName(qr_image_generator)
        self.timer = QtCore.QTimer()
        self.timer.setInterval(1000)
        self.timer.timeout.connect(self.generate)
        self.timer.start()

    def retranslateUi(self, qr_image_generator):
        _translate = QtCore.QCoreApplication.translate
        qr_image_generator.setWindowTitle(_translate("qr_image_generator", "MainWindow"))
        self.sure.setText(_translate("qr_image_generator", "SÜRE"))
        self.qr_kod.setText(_translate("qr_image_generator", "KOD"))
        self.qr_resim.setText(_translate("qr_image_generator", "RESİM"))
    sayac = 6
    def generate(self):
        if self.sayac == 0:
            self.sayac = 6
        self.sayac -= 1
        self.sure.setText(str(self.sayac))
        if self.sayac == 5:
            code = qr_code_generator.randomize()
            self.qr_kod.setText(code[len(qr_code_generator.initial_code):])
            qr.clear()
            qr.add_data(code)
            qr.make(fit = True)
            qrimg = qr.make_image(fill_color = "black", back_color = "white")
            byte_stream = BytesIO()
            qrimg.save(byte_stream, format = 'PNG')
            image = QImage()
            image.loadFromData(byte_stream.getvalue())
            pixmap = QPixmap.fromImage(image)
            pixmap = pixmap.scaled(self.qr_resim.size(),
                                Qt.KeepAspectRatio, Qt.SmoothTransformation)
            self.qr_resim.setPixmap(pixmap)
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qr_image_generator = QtWidgets.QMainWindow()
    ui = Ui_qr_image_generator()
    ui.setupUi(qr_image_generator)
    qr_image_generator.show()
    sys.exit(app.exec_())
